import './src/styles.js'
import './src/components/dice-button.js'
import './src/components/dice-die.js'
import './src/components/dice-input.js'
import './src/components/dice-picker.js'
import './src/components/dice-root.js'
import './src/components/dice-toolbar.js'
import './src/components/dice-tray.js'
